### ISSUE TITLE
2021_Metabolomics C18 Methods Evaluation

### ISSUE THREAD

**Issue by YonghuiDong** [YonghuiDong/BCDD_Research#1]
## Objective

Compare 3 different LC methods for Metabolomics studies

## Materials and Methods

- Human serum is used for method evaluation.

- 3 different LC methods (see below) with the same MS method

## MS Method

Parameter | Positive | Negative
-- | -- | --
Spray Voltage (KV) | 3.8 | 3.0
Capillary Temperature (°C) | 320 | 320
Aux gas heater temperature (℃) | 350 | 350
Sheath Gas Flow Rate (Arb) | 35 | 35
Aux gas flow rate (Arb) | 8 | 8
S-lens RF level | 50 | 50
Mass range (m/z) | 70-1050 | 70-1050
Full MS resolution | 70000 | 70000
Number of microscans  | 1 | 1
AGC target (full scan) | 1e6 | 1e6
maximum injection time (full scan) | 100 ms | 100 ms
MS/MS resolution | 17500 | 17500
Isolation window | 1 Da | 1 Da
AGC target (dd-MS2) | 5e4 | 5e4
maximum injection time (dd-MS2) | 50 ms | 50 ms
NCE/stepped NCE | 10，20，40 | 10，20，40

## Sample extraction method

Six serum samples were thawed at room temperature. 300 μl ACN and MeOH (ACN/MeOH, 2:1, V/V) was added into serum (100 μL), vortex-mixed for 1 min, sonicated with cold water at 4°C for 10 min, and cooled at -20°C for 1 h for protein precipitation. After centrifugation at 13,000 rpm for 10 min at 4 °C, the supernatant (300 μL) was pipetted out and dried using SpeedVac (~ 1.5h). The residues were dissolved in 300 μL MeOH : water (80 : 20). Then the samples were vortex-mixed for 1 min; After centrifugation (14,000 rpm, 10 min, 4 °C), the supernatant was filtered through a 0.22 μm PTFE membrane filter.

In order to account for any variations during sample preparation. The 6 samples were first homogeneously mixed and then aliquoted into 6 vials and stored at -80°C before LCMS analysis.

 The injection volume was ~~2 μL~~ 5 μL.

Both mobile phase solutions were sonicated for 30 min in an ultrasonic bath. Sonication helps to enhance dissolution of chemicals and mix all of the solution components securing the homogeneity of the mobile phase. Sonication will also remove dissolved air bubbles in the solution.

## Experiment Plan

20 injections (10 for each ion mode) for each method in order to evaluate the following parameters:

- Number of Peaks

- Peak Area/Intensity

- Stability (RT, mass, intensity)

- Repeatability 

- No. of MS2 events

- Peak matching

## Todo and Progress
- [x] Prepare LC methods
- [x] Finalize MS method (Deadline 16, August, 2021)
- [x] Prepare columns
- [x] Serum sample extraction
- [x] Run method 1 (Deadline: 17th August, 2021)
- - [x] Calibrate MS
- - [x] Install and equilibrate column
> Note: ~~the initial sample injection volume was 2 μL, but I found that the number of detected peaks are very limited, and 5 μL injection showed much better result.~~ So Method 1 was re-run using 5μL injection (updated on 16th August). The above reason may be not correct. What I have found is that even with 5μL injection, I can only get good result (enough amount of peaks) for the first injection. I have repeatedly injected the sequence 3 times, and only the first injection has good amount of peaks, the rests are very similar as blank. After dufferent tests, I conclude that it is because method 1 is not good. The reconditioning time is method 1 is very short (only 1 min), and it affects the results! (maybe the samples are washed away. I have no idea). After adding an extra 3 min for reconditioning, and it works! (updated on 19th August)

- [x] Run method 2  (Deadline: 19th August, 2021)
- - [x] Calibrate MS
- - [x] Install and equilibrate column
- [x] Run method 3  (Deadline: 18th August, 2021)
- - [x] Calibrate MS
- - [x] Install and equilibrate column
- [x] Analyze Data
- [x] Compare the 3 methods
- [x] Draw conclusion and prepare report

## Result

The code and final results are save in this [folder](https://github.com/YonghuiDong/BCDD_Research/tree/main/%231_2021_Metabolomics%20C18%20Methods%20Evaluation).

## Conclusion

In general, Method 1 gives the best result, followed by Method 3. The performance of method 2 is relatively poor for our instrumentation.

However, Method 3 has the shortest LC running time (Method 1 of 19 min, Method 2 of 15 min and Method 3 of 14 min), and the number of reliable features obtained from Method 3 is very close to Method 1 (or even better in some cases). `RawHummus` results also show that Method 3 has the best stability (See **Results** folder for details). I personally prefer Method 3, and I believe that Method 3 will perform better if the LC running time is the same as Method 1 (Method 3 could be modified a bit to get better result).

**Comment by YonghuiDong** [comment]
## LCMS C18 Method 1:

**Column**:  ACQUITY UPLC HSS T3 （100 mm×2.1 mm, 1.8 um)

**Column Temperature**:  45℃

**Mobile phase A**:  Water (containing 0.1 % formic acid, v/v)

**Mobile phase B**: Acetonitrile (containing 0.1 % formic acid, v/v)

Separation was achieved using the following gradient: 

|Time (min)  | Flow (ml/min) | A% | B% |
| ------------- | ------------- | ------------- |------------- |
| 0 | 0.35 | 95  | 5  | 
| 2 | 0.35 | 95  | 5  | 
| 4 | 0.35 | 75  | 25 | 
| 8 | 0.35 | 50  | 50  | 
| 10 | 0.35 | 20 | 80  | 
| 14 | 0.35 | 0  | 100  | 
| 15 | 0.35 | 0  | 100  | 
| 15.1 | 0.35 | 95  | 5  | 
| 16 | 0.35 | 95  | 5  | 

Here I added 3 extra min (update on 19th August)
|Time (min)  | Flow (ml/min) | A% | B% |
| ------------- | ------------- | ------------- |------------- |
| 17 | 0.35 | 95  | 5  | 
| 18 | 0.35 | 95  | 5  | 
| 19 | 0.35 | 95  | 5  | 

All the samples were kept at 4℃ during the analysis.

## Column Care

[HSS T3 column care.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7012516/HSS.T3.column.care.pdf)

## Reference

[LCMS_Method_Luming.pdf](https://github.com/YonghuiDong/BCDD_Research/files/6974236/LCMS_Method_Luming.pdf)

**Comment by YonghuiDong** [comment]
## LCMS C18 Method 2:

**Column**: Hypersil GOLD aQ UPLC column (100 × 2.1 mm, 1.9 μm, Thermo Fisher Scientific, Part No. 25302-102130)

**Column Temperature**: 45℃

**Solvent A**: Mobile phase A consists of 0.1% formic in water (v/v). Mix 1000.0 mL of water with 1.0 mL of formic acid.

**Solvent B**: Mobile phase B consists of 0.1% formic acid in methanol (v/v). Mix 1000.0 mL of methanol with 1.0 mL of formic acid.

Separation was achieved using the following gradient:

| Retention (min) | Flow (mL/min) | %A | %B | Curve |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 0 | 0.3 | 99.0 | 1.0 | 5 |
| 0.5 | 0.3 | 99.0 | 1.0 | 5 |
| 2 | 0.3 | 50.0 | 50.0 | 5 |
| 10.5 | 0.3 | 1.0 | 99.0 | 8 |
|11.0 | 0.400 | 1.0 | 99.0 | 5 |
|11.5| 0.400 | 99.0| 1.0 | 7 |
|14.9 | 0.400 | 99.0 | 1.0 | 5 |
|15.0 | 0.300 | 99.0 |1.0 |  5 |

> **Note**: The “curve” parameter in the LC method settings defines how the composition of the mobile phase is changed. The value “5” stands for a linear change between two points of the gradient. The further the value is from “5,” the more hyperbolic the curve gets. The settings of the “curve” parameter may change the compound elution order dramatically

## Column Care

[HypersilGOLD-Care.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7012505/HypersilGOLD-Care.pdf)


## Reference

[LCMS_Method_University of Birmingham.pdf](https://github.com/YonghuiDong/BCDD_Research/files/6974117/LCMS_Method_University.of.Birmingham.pdf)

**Comment by YonghuiDong** [comment]
## LCMS C18 Method 3

**Column**: ACQUITY HSS T3(2.1×100mm, 1.8 um)

**Column Temperature**: 45℃ 

**Mobile phase A**:  0.1% formic in water (v/v). 

**Mobile phase B**: 0.1% formic acid in acetonitrile (v/v).

|Time (min)  | Flow (ml/min) | A% | B% |
| ------------- | ------------- | ------------- |------------- |
| 0 | 0.35 | 95  | 5  | 
| 10 | 0.35 | 10  | 90  | 
| 11 | 0.35 | 10  | 90 | 
| 11.1 | 0.35 | 95  | 5  | 
| 14.0 | 0.35 | 95  | 5  | 

All the samples were kept at 4℃ during the analysis.

## Column Care

See [Method 1](https://github.com/YonghuiDong/BCDD_Research/issues/1#issuecomment-897395724)

## Reference

[LCMS_Method_Maiwei.pdf](https://github.com/YonghuiDong/BCDD_Research/files/6978229/LCMS_Method_Maiwei.pdf)
