### ISSUE TITLE
2021_Targeted Analysis of Energy Metabolites

### ISSUE THREAD

**Issue by YonghuiDong** [YonghuiDong/BCDD_Research#2]
## Objective

Our previous LCMS method works very well. But the addition of dibutylamine as modifier heavily contaminates the LCMS system and it is very difficult to get rid of it. As such, the persistance of dibutylamin peak at positive ion mode (_m/z_ 130.159) largely affects other LCMS studies. 

The objective of this project is to set up/optimize a targted LCMS method for 12 different energy metabolites.

## Materials and Methods

10 energy metabolites standards, i.e., NAMD, NIAC, NAD, NADH, NADP, NADPH, ADPR, AMP, ADP, and ATP, are used for method evaluation.

Column: Hypercarb (100 x 2.1 mm, particle size 3 um. [catalog number: 35003-102130](https://www.thermofisher.com/order/catalog/product/35003-102130#/35003-102130)). My previous tests showed that hypercarb column offered the best sensitivity and seperation among few other columns. Therefore only hypercarb column is used for method setup/optimization.

[Hypercarb Column Care and Use.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7081828/Hypercarb.Column.Care.and.Use.pdf)

## Some Current Issues

- [x] Carryover/contamination of the column
- [ ] Peak shape for some metabolites (e.g., ATP) were not good
- [ ] Some metabolite peaks are splited (e.g., NAD), need to check possible reasons
- [ ] Nicotinamide (NAMD) was not detected
- [x] There might be interconversions among some metabolites (NAD to cADPR and ADPR?)

## Todo and Progress

- [x] Wash column (Done on 31st, 08, 2021. Note that I did no perform step 2 as I don't have dibutylether at the moment)

**Strong organic wash** 

The strong organic wash is suitable for applications involving polar and/or ionizable species chromatographed in an aqueous eluent:
1. Flush column at 1.0 mL/min with 50 mL of acetone
2. Flush column at 1.0 mL/min with 120 mL of dibutylether
3. Flush column at 1.0 mL/min with 50 mL of acetone
4. Re-equilibrate column with aqueous mobile phase

- [x] Test method 1
- [x]  Test method 2
- [x] Test method 3

See below for details.

- [ ]  Sample extration method

## Conclusions

**Comment by YonghuiDong** [comment]
# Method 1

**Column**: 2.1 mm x 50 mm Hypercarb

**Column Temperature**: 30°C

**Maximum Pressure**: 900 bar

**Flow Rate**: 0.65 mL/min

**Phase A**: 10 mM ammonium acetate, pH 9.5

**Phase B**: Acetonitrile

|Time (min)  | Flow (ml/min) | A% | B% |
| ------------- | ------------- | ------------- |------------- |
| 0 | 0.65 | 95  | 5  | 
| 1 | 0.65 | 91  | 9  | 
| 2 | 0.65 | 40  | 60 | 
| 2.1 | 0.80 | 5  | 95  | 
| 2.7 | 0.80 | 5 | 95  | 
| 2.8 | 0.70 | 95 | 5  | 
| 3.9 | 0.70 | 95  | 5  | 
| 4.0 | 0.65 | 95  | 5  | 

## Reference

[Method1-University of Florida.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7081917/Method1-University.of.Florida.pdf)

**Comment by YonghuiDong** [comment]
# Method 2

**Column**: 2.1 mm x 150 mm Hypercarb

**Column Temperature**: 35°C

**Flow Rate**: 0.2 mL/min

**Mobile Phase A**: 2 mmol/L ammonium acetate in water, pH adjusted to 10

**Mobile Phase B**:  2 mmol/L ammonium acetate in acetonitrile, pH adjusted to 10

|Time (min)  | Flow (ml/min) | A% | B% |
| ------------- | ------------- | ------------- |------------- |
| 0 | 0.2 | 98  | 2  | 
| 2 | 0.2 | 98  | 2  | 
| 4 | 0.2 | 85  | 15 | 
| 10 | 0.2 | 85  | 15  | 
| 13 | 0.2 | 50 | 50  | 
| 13.1 | 0.2 | 98 | 2  | 
| 20 | 0.2 | 98  | 2  | 

## Results and Discussion

## Reference

[Method 2-Simultaneous determination of adenine nucleotides, creatine phosphate andcreatine in rat liver by high performance liquid chromatography–electrosprayionization-tandem mass spectrometry.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7081984/Method.2-Simultaneous.determination.of.adenine.nucleotides.creatine.phosphate.andcreatine.in.rat.liver.by.high.performance.liquid.chromatography.electrosprayionization-tandem.mass.spectrometry.pdf)

**Comment by YonghuiDong** [comment]
# Method 3

**Column**: 1 mm x 100 mm Hypercarb

**Column Temperature**: 60°C

**Flow Rate**:  0.35 mL/min (Note that in the reference the authors used 1 mm x 100 mm Hypercarb and the flow rate is 0.08 mL/min; Our column is 2.1 mm x 100 mm Hypercar, so the flow rate is adjusted to 0.35 mL/min. F<sub>C2</sub> = d<sup>2</sup><sub>C2</sub> / d<sup>2</sup><sub>C1</sub> * F<sub>C1</sub>)

**Mobile Phase A**: 7.5 mM ammonium acetate with 0.05% (v/v) ammonium hydroxide

**Mobile Phase B**:  0.05% (v/v) ammonium hydroxide in acetonitrile

|Time (min)  | Flow (ml/min) | A% | B% |
| ------------- | ------------- | ------------- |------------- |
| 0 | 0.35 | 95  | 5  | 
| 1.8 | 0.35 | 95  | 5  | 
| 14 | 0.35 | 46  | 54 | 
| 14.1 | 0.35 | 15  | 90  | 
| 17.1 | 0.35 | 10 | 90  | 
| 17.2 | 0.35 | 95 | 5  | 
| 32.2 | 0.35 | 95  | 5  | 

Equilibrate the column for 20 min with solvent A1 before the first injection.  After sample injection, apply solvent B1 on a gradient.

### Results and Discussion

This method doesn't work well.

## Reference

[Method 3-Targeted, LCMS-based Metabolomics for Quantitative Measurement of NAD+ Metabolites.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7082044/Method.3-Targeted.LCMS-based.Metabolomics.for.Quantitative.Measurement.of.NAD%2B.Metabolites.pdf)

[Method 3-Assays for NAD+-Dependent Reactions and NAD+.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7084683/Method.3-Assays.for.NAD%2B-Dependent.Reactions.and.NAD%2B.pdf)

**Comment by YonghuiDong** [comment]
## Issue 1: Carryover/contamination of the column

### Description 

After washing with acetone (See [Todo and Progress](https://github.com/YonghuiDong/BCDD_Research/issues/2#issue-974968681)). Most energy metabolites were washed out except AMP. There is still a relatively huge AMP peak in Blank (both Positive and Negative ion mode, using Method 3).

I have also tested the carryover/contamination using method 2. Only AMP can be detected. The strange thing is that RT of AMP in blank is about 15.30 min, while it is 11.86 min in mix standard. 

![BLK](https://user-images.githubusercontent.com/22663189/133056293-6b393ca6-3708-4160-93ee-e8b4e4fdd635.JPG)

Fig.1 AMP peak in Blank

![Std Mix](https://user-images.githubusercontent.com/22663189/133056406-19d76bf3-3a19-42f3-8d10-0049a891c157.JPG)

Fig.2 AMP peak in standard mix (concentration 1000 ng/ml)

**Update on 14 September 2021**

The column is washed again following the **Strong organic wash** protocol, except that 0.5ml/ml dibutylether was used due to the reason that 1.0ml/ml dibutylether leads to excess of pressure limit.

![BLK_AfterWash](https://user-images.githubusercontent.com/22663189/133926452-80a12819-c57b-430f-9605-89d228b4ff61.JPG)

Fig. 3 No AMP peak detected in Blank

### Conclusion

1. **Strong Organic Wash** Method works very well. I can use it for the future Hypercarb column cleaning.

> During column cleaning with 1ml/min  dibutylether, leakage in the joint of pre-column was observed. So I disassembled the pre-column. But pressure limit was exceeded. So I used 0.5ml/min dibutylether for column cleaning. This has to be paid attention during future column cleaning.

2. When I tested the cleaning result, I did not use pre-column. Because the contamination of pre-column could also lead to detection of contaminated peaks in Blank. The absence of pre-column may also contribute to the result shown in Fig. 3.

**Comment by YonghuiDong** [comment]
## Issue 4: There might be interconversions among some metabolites (NAD to cADPR and ADPR?)

### Description

Indeed I have detected cADPR and ADPR peaks again using method2 even though their standards are absent; The two peaks are not found in Blank samples.

![cADPR](https://user-images.githubusercontent.com/22663189/133057985-49127263-21e5-4c88-8095-ff84f8dda405.JPG)

Fig.1 cADPR peak found in standard mix

![ADPR](https://user-images.githubusercontent.com/22663189/133058107-ed47c3d8-11c6-4e3e-8c07-444f633c7931.JPG)

Fig. 2 ADPR peak found in standard mix

### Problem Detection

To check if cADPR and ADPR were converted (nonenzymatically) from NAD. I have prepared a NAD standard solution (1000 ng/ml), and analysed it using LCMS to check if cADPR and ADPR can be detected. Blank was used as control.

As shown in Fig. 3 and 4, both cADPR and ADPR were detected in NAD standard. By contrast, they were not found in blank samples.

So I can conclude that cADPR and ADPR are converted from NAD!

![cADPR detected in NAD](https://user-images.githubusercontent.com/22663189/133078658-7c452ffb-506d-45ba-b113-172a5fab0a42.JPG)

Fig. 3 cADPR peak detected in NAD standard

![ADPR detected in NAD](https://user-images.githubusercontent.com/22663189/133078702-b2a759fe-6fd2-4054-9f03-417f5cbadbdf.JPG)

Fig. 4 ADPR peak detected in NAD standard

![cADPR peak in blank](https://user-images.githubusercontent.com/22663189/133079777-a4ca1012-be18-4191-8aba-6e28eb3bfd24.JPG)

Fig. 5 cADPR in Blank

![ADPR in blank](https://user-images.githubusercontent.com/22663189/133079849-533d62ea-64ed-429c-a421-cb60886f95b8.JPG)

Fig. 6 ADPR in Blank

#### Further tests

I have also analyzed NADH, NADP and NADPH standard individually. I found that NADH can also concert to cADPR and ADPR. 

## Where and how does the conversion happen?

Seeing from the RT difference between NAD, cADPR and ADPR, I guess this conversion happens before LC. Otherwise they will have exactly the same RT (e.g., if cADPR and ADPR are in-source fragments of NAD).

![NAD](https://user-images.githubusercontent.com/22663189/133272482-6143f965-aedf-4185-82b1-7ad32ed3180e.JPG)

Fig. 7 LCMS of NAD standard

So I performed a direct injection of NAD standard solution, and indeed cADPR and ADPR peaks were detected.

![DI_NAD](https://user-images.githubusercontent.com/22663189/133274707-1ef4c55e-a319-4a29-9c51-386b1c752eb7.JPG)

Fig. 8 Direct injection of NAD standard

The result indicates that the conversion happened in NAD standard, either because NAD is not pure or during storage NAD can convert to cADPR and ADPR.

**Comment by YonghuiDong** [comment]
## Method 4

**Column**: 100 x 2.1 mm, particle size 3 um Hypercarb

**Column Temperature**: 25°C

**Flow Rate**:  0.25 mL/min

**Mobile Phase A**:  Ammonium acetate,  pH 8.8

**Mobile Phase B**:  ACN

|Time (min)  | Flow (ml/min) | A% | B% |
| ------------- | ------------- | ------------- |------------- |
| 0 | 0.25 | 100  | 0  | 
| 2 | 0.25 | 100  | 0  | 
| 5 | 0.25 | 100 | 50 | 
| 7 | 0.25 | 100  | 50  | 
| 7 | 0.25 | 100 | 0  | 
| 10 | 0235 | 100 | 0  | 

This method may only works for ATP, ADP and AMP
