### ISSUE TITLE
2021_MALDI Imaging of Fmoc-FF

### ISSUE THREAD

**Issue by YonghuiDong** [YonghuiDong/BCDD_Research#4]
## Objective

Hydrogel is used for bone regeneration and we would like to see if we can see residues of the hydrogel using MALDI imaging and LCMS

### Hydrogel preperation (For MALDI Imaging)

- 100 mg/ml Fmoc-FF in DMSO (stock solution)
- Dilute the stock solution with water to 5 mg/ml. It will form hydrogel in few minites.
- The hydrogel can be then sectioned for MALDI imaging

### Fmoc-FF solution for LCMS

This targted analysis aims at (1) develop a quantitative method for Fmoc-FF, and (2) determine the LOD of Fmoc-FF.

- xx mg/ml Fmoc-FF in DMSO is used for LCMS.

## Todo and Progress

- [x] MALDI imaging of the Hydrogel

- [ ] LCMS method set

- [ ] LCMS quantification (calibration curve construction)

**Comment by YonghuiDong** [comment]
## MALDI imaging of the Hydrogel

What I did was to place a droplet of FmocFF hydrogel (5mg/ml) on the glass slide, and analyse the droplet with MALDI imaging. FmocFF was detected at positive ion mode [M+H]+. 


![FmocFF_MALDI](https://user-images.githubusercontent.com/22663189/134363126-b6bab188-18ff-40e8-9bf4-7acbe1741dac.png)

Fig. 1 MALDI imaging of FmocFF.
