### ISSUE TITLE
2021_LCMS Method Setup for Quinolinic Acid and Sample Analysis @ Lihi Gershon

### ISSUE THREAD

**Issue by YonghuiDong** [YonghuiDong/BCDD_Research#5]
## Objective

Set up a LCMS method for quinolic acid

### Todo and Progress

- [x] Direct injection of quinolic acid to optimize MS method
- [x] LCMS analysis of quinolinic acid to set up LC method
- [x] Optimize LCMS method
- [x] Define linear dynamic range, LLOD and LLOQ
- [x] Test on real biological samples (Date: 20111108)
- [x] Analyse biological samples (Date: 20111109)
- [x] Data Analysis (Date: 20111110)
- [x] Report (Date: 20111110)

**Comment by YonghuiDong** [comment]
## Material and Method

### 1. Std solution

0.1 mg/ml quinolinic acid stock solution was prepared by adding quinolinic acid standard in 1 mg/mL citric acid solution.

1000 ng/ml quinolinic acid was prepared by diluting the stock solution in 0.01 mg/ml citric acid solution and it was used for the method setup


### 2. LC Method

**Column**:  HSS T3 1.8 μm with dimensions 2.1 × 100 mm

**Column temperature**: 45°C

**Mobile phase A**:  0.1% formic acid in water (UPLC grade) 

**Mobile phase B**: 0.1% formic acid in acetonitrile (UPLC grade). 


|Time (min)  | Flow (ml/min) | A% | B% |
| ------------- | ------------- | ------------- |------------- |
| 0 | 0.5 | 99  | 1  | 
| 3 | 0.5 | 90  | 10  | 
| 4 | 0.5 | 10  | 90 | 
| 4.1 | 0.5 | 99  | 1  | 
| 7 | 0.5 | 99 | 1 | 

Flow rate was 0.5 ml/min, and the autosampler is set at 10°C. 

**HSS T3 column care**

[HSS.T3.column.care.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7336501/HSS.T3.column.care.pdf)

**Reference**

[Quinolinic acid.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7336471/Quinolinic.acid.pdf)

**Comment by YonghuiDong** [comment]
## Result

### 1. Direct Injection

Positive mode shows more stable and higher peak compared to that in negative ion mode

![Pos](https://user-images.githubusercontent.com/22663189/137112269-ef313257-84d4-4679-b0c9-0bb0ef3f6f8a.JPG)

Fig1. Quinolinic acid peak detected at positive ion mode ([M+H+])

![Neg](https://user-images.githubusercontent.com/22663189/137112393-630e157e-5d62-41a6-833c-cbaba74d010c.JPG)

Fig2. Quinolinic acid peak detected at negative ion mode ([M-H-])

> Note: The MS methods were my C18 MS methods except that SIM mode was used here

### 2. LCMS

Quinolinic acid can be well detected with the above LCMS method. 

![LCMS_Quinolinic](https://user-images.githubusercontent.com/22663189/137127658-3ec857cf-7dda-41a9-a514-d12826f9e96c.JPG)

Fig. 3 Chromatogram and mass spectrum of Quinolinic acid 

![BLK](https://user-images.githubusercontent.com/22663189/137131004-3e38f22f-d0f2-42cb-84c2-59849e55e8ec.JPG)

Fig. 4 Quinolinic acid was not detected in BLK (0.01 mg/ml citric acid solution was used as blank)

I did 6 injections to check RT and Peak Area variations.

Here is the result:

|Metabolite  | Concentration | Mean RT | Mean Peak Area | RSD of RT (%) | RSD of Peak Area  (%) | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Quinolinic Acid |  1000 ng/ml | 0.87  | 2.82e7  | 0  |  7.1 |

**Comment by YonghuiDong** [comment]
## LC method optimization

Since quinolinic acid was detected at 0.87 min, I can reduce the previous method.

Here is the new LC method

|Time (min)  | Flow (ml/min) | A% | B% |
| ------------- | ------------- | ------------- |------------- |
| 0 | 0.5 | 99  | 1  | 
| 1 | 0.5 | 96  | 4  | 
| 1.1 | 0.5 | 99  | 1 | 
| 4 | 0.5 | 99  | 1  | 

### Result

Quinolinic acid can be well detected with the modified LC method as well.

![LCMS_Quinolinic2](https://user-images.githubusercontent.com/22663189/137135307-5213788f-b9ab-4c61-a5ad-7f78f2d1213d.JPG)

Fig. 5 Chromatogram and mass spectrum of Quinolinic acid with optimized LC method

![BlK2](https://user-images.githubusercontent.com/22663189/137135524-11d24759-7ee0-4d35-a643-6fee84d10814.JPG)

Fig. 6 Quinolinic acid was not detected in BLK (0.01 mg/ml citric acid solution was used as blank) with the modified method

I also did 6 injections to check RT and Peak Area variations with this new method.

Here is the result:

|Metabolite  | Concentration | Mean RT | Mean Peak Area | RSD of RT (%) | RSD of Peak Area  (%) | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Quinolinic Acid |  1000 ng/ml |  0.94 |  3.62E7 |  0 | 2.8  |

### Conclusion

This method is even better: shorter LC, higher Peak Area and smaller RSD of Peak Area!

**Comment by YonghuiDong** [comment]
## Linear dynamic range determination

Quinolinic stock solution (S):  0.1 mg/ml  (by adding quinolinic acid standard in 1 mg/mL citric acid solution)

11 Serial dilutions of quinolinic: from **S/2 (50000 ng/ml)** ~ **S/2^11 (48.8 ng/ml)**

## Results

> Due to my wrong calculation, my lowest concentration is 48.8 ng/ml, so I need to add more points to determine LLOD

As shown in Fig. 7 that the Quinolinic acid Concentration-Response curve is not linear. So I selected 2 linear dynamic ranges, shown in Fig. 8 and 9.

![image](https://user-images.githubusercontent.com/22663189/137337499-35949b40-6022-4013-b38d-9bd5168770f7.png)

Fig. 7 Quinolinic acid Concentration-Response curve (all 11 concentration levels)

![image](https://user-images.githubusercontent.com/22663189/137333059-d77e1786-7bfb-4b91-a650-ad90068730df.png)

Fig. 8 Quinolinic acid calibration curve (48.8 - 1562.5 ng/ml, 6 points)

![image](https://user-images.githubusercontent.com/22663189/137337985-aa73faa5-986e-439c-8dbc-e9ca46fd4354.png)

Fig. 9 Quinolinic acid calibration curve (3125 - 25000 ng/ml, 4 points)

**Comment by YonghuiDong** [comment]
## Test on biological sample

### Sample extraction

**Extraction Solvents :**

- Solvent 1: ACN and MeOH (ACN/MeOH, 2:1, V/V) containing 10 mM ammonium formate (for protein precipitation)

> 9 mL solvent 1: 6mL ACN, 3ml MeoH and 5.68 mg ammonium formate

- Solvent 2: Water containing 10mM ammonium formate and 0.5% formic acid (for extraction and resuspension)

> 9 mL solvent 2: 9mL water, 45ul formic acid

Serum samples were thawed at room temperature. 300 μl Solvent 1 was added into serum (100 μL), vortex-mixed for 1 min, sonicated with cold water at 4°C for 10 min, and cooled at -20°C for 1 h for protein precipitation. After centrifugation at 13,000 rpm for 10 min at 4 °C, the supernatant (300 μL) was pipetted out and dried using SpeedVac (~ 1.5h). 

Dry extracts were resuspended in 300 μL of water containing 10 mM ammonium formate and 0.5% formic acid. Then the samples were vortex-mixed for 1 min; After centrifugation (14,000 rpm, 10 min, 4 °C), the supernatant was filtered through a 0.22 μm PTFE membrane filter.

Five μL of each well was injected onto the LCMS system for analysis.

> Note: The method is adopted from my previous C18 method (precipitation) and the above [reference](https://github.com/YonghuiDong/BCDD_Research/issues/5#issuecomment-942051960).

### Result

![sample](https://user-images.githubusercontent.com/22663189/140773495-c05e7546-67c2-4d4e-864e-0979d20de87a.JPG)

Fig.10 Quinolinic acid from rabbit serum

Quinolinic acid was detected from rabbit serum sample, but the peak area is quite low

**Comment by YonghuiDong** [comment]
## Sample Analysis

### Sample extraction

See https://github.com/YonghuiDong/BCDD_Research/issues/5#issuecomment-943417030

> **Note**: In order to concentrate the samples, here **350 ul** supernatant was pipetted out and dried using SpeedVac (~ 2h). And dry extracts were resuspended in **200 μL** of water containing 10 mM ammonium formate and 0.5% formic acid. Sample were centrifuged (14,000 rpm, 20 min, 4 °C) without filteration.

### Calibration solution

see https://github.com/YonghuiDong/BCDD_Research/issues/5#issuecomment-942992806

10 serial dilutions: 1000 ng/ml to 1000/2^9 = 1.95 ng/ml (2^0 - 2^9)

### Results

See the [result and report](https://github.com/YonghuiDong/BCDD_Research/tree/main/%235_2021_Quinolinic%20acid/Script) folder for details.
