### ISSUE TITLE
2021_LCMS Method Setup for Dolichols @Moshe Giladi, @Yoni Haitin

### ISSUE THREAD

**Issue by YonghuiDong** [YonghuiDong/BCDD_Research#6]
## Objective

Identify and quantify Dolichols

## Todo and Progress

- [x] Direct injection of dolichols to optimize MS method
- [x] LCMS method setup
- [x] LCMS method optimization

**Comment by YonghuiDong** [comment]
## Direct Injection

### Standards

[Dolichol Mixture (13~21)](https://avantilipids.com/product/900200). 


<img src="https://user-images.githubusercontent.com/22663189/141697531-5ce0fb70-7c53-471a-a920-e85b78be3446.png" width="400">

> General chemical formula of Dolichol is (C5H8)n-H4O

- Mother solution, 1 mg/ml, (1 mg of Dolichol 13-21 in 1 ml of Mobile phase B) 
- 1000 ng/ml (x 1000 dilution) is used for direct injection

| Name |Formula | Mass| [M+H]+| [M+NH4]+
| -- | -- | -- | -- | -- |
| Dolichol-21 |   C105H172O | 1449.341 | 1450.3481 | 1467.3746 |
 | Dolichol-20  | C100H164O | 1381.278 | 1382.2855 | 1399.3120 |
 | Dolichol-19 | C95H156O | 1313.216 | 1314.2229 | 1331.2494 |
 | Dolichol-18 | C90H148O | 1245.153 | 1246.1603 | 1263.1868 |
| Dolichol-17 | C85H140O | 1177.0904 | 1178.0977 | 1195.1242|
| Dolichol-16 |  C80H132O | 1109.028 |  1110.0351 | 1127.0616 |
| Dolichol-15 |  C75H124O |  1040.965 |  1041.9725 | 1058.9990 |
| Dolichol-14 | C70H116O  | 972.9026 | 973.9100 | 990.9364 |
| Dolichol-13 | C65H108O  |  904.840 | 905.8473 | 922.8738 |

## Result

Dolichol standard mixture of concentration 1 mg/mL can be detected (Fig. 1). However, the standard mixture of concentration 10 ug/mL and 1 ug/mL were not detected.

![Dolichol Mixture](https://user-images.githubusercontent.com/22663189/141804670-4f670c1e-0ac6-45b8-8cb0-7b2808fc181b.png)

Fig. 1 MS for dolichol standard mix (1 mg/mL)

## Todo

2021.12.06

- [x] Need to check why addition of NH4Ac did not work 

It works with solvent A.

- [x] Why Dols were not detected at lower concentration (i.e.g, 10 ug/mL and 1 ug/mL)

Dols were well detected at 10,000, 1000, 100, 10 and 1 ng/mL. See Figures below for details.

![1ug_pos](https://user-images.githubusercontent.com/22663189/144857324-810eb32a-7f8b-4fbf-8d88-bf1199f5cea9.JPG)

Fig. 2 MS for dolivhol standard mix (**1000 ng/mL**).

![1ng](https://user-images.githubusercontent.com/22663189/144858184-1898983c-1fdb-4410-926c-47b614ff99c7.JPG)

Fig. 3 MS for dolivhol standard mix (**1 ng/mL**).

- [x] Positive mode or negative mode? 

Positive ion mode is better in both ion intensity and No. of detected standards

![2mM Neg](https://user-images.githubusercontent.com/22663189/146164228-218f239b-12fb-4f74-96df-7738017cf626.png)


Fig. 3 MS for dolivhol standard mix at negative ion mode (**1000 ng/mL**).

**Experiment**

- Solvent A: 1 mM Ammonium acetate in mobile phase A (3.854 mg in 20 mL mobile phase A)
-  10 ug/mL (x 100) and 1 ug/mL (x 1000) Dols standard mix solution is used

**Comment by YonghuiDong** [comment]
## LCMS method setup  (❌)

**Column**: 100mm x 2.1mm HSS T3 C18 column (Waters)

[HSS T3 column care.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7880143/HSS.T3.column.care.pdf)

**Mobile phase A**: methanol and water mixture (9:1, v/v) , A9 (with 2mM ammonium accetate added, updated on 17th, Jan, 2022)

**Mobile phase B**: methanol:isopropanol:hexane (2:1:1, v/v/v) , C

|Time (min)  | Flow (ml/min) | A% | C% |
| ------------- | ------------- | ------------- |------------- |
| 0 | 0.4 | 100 | 0  | 
| 10 | 0.4 | 25 | 75  | 
| 15 | 0.4 | 10  | 90 | 
| 16 | 0.4 | 0  | 100  | 
| 17 | 0.4 | 100 | 0 | 
| 20| 0.4 | 100 | 0 | 

MS: Positive ion mode

**Reference**

[Dolichol.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7496557/Dolichol.pdf)

## Reason

We don't have the BEH C18 column (Waters) as described in the reference. HSS T3 with this LC mobile phase condition is not working well

**Comment by YonghuiDong** [comment]
## Check the effect of ammonium acetate on the detection of Dols

### Objective

With 1mM ammonium acetate, we can detect Dols quite well. See [here](https://github.com/YonghuiDong/BCDD_Research/issues/6#issuecomment-963047947) for details. We would like to understand that if the increase of ammonium acetate concentration would improve the detection of Dols

### Experiment

- [x] 1 mM ammonium acatate (3.854 mg in 20 mL solvent A)

See Figure 3, 5 Dols were detected.

- [x] 2 mM ammonium acetate (7.7 mg in 20 mL solvent A)

![2mM](https://user-images.githubusercontent.com/22663189/144861229-47e8fd34-d3e4-4b11-9ad8-6dbab95395fd.JPG)

Fig. 4 MS for dolivhol standard mix (10 ng/mL) with 2 mM ammonium acetate.

- [x] 3 mM ammonium acetate (11.56 mg in 20 mL solvent A)

![3 mM](https://user-images.githubusercontent.com/22663189/144861281-67bd3e78-2723-4eca-be6b-e9a32c02a4d8.JPG)

Fig. 5 MS for dolivhol standard mix (10 ng/mL) with 3 mM ammonium acetate.

- [x] 5 mM ammonium acetate (19.27 mg in 20 mL solvent A)

![5 mM](https://user-images.githubusercontent.com/22663189/144861764-37bc2d00-bfa4-45b5-addd-5f4371cf22cc.JPG)

Fig. 6 MS for dolivhol standard mix (10 ng/mL) with 5 mM ammonium acetate.

- [x] 20 mM ammonium acetate (77.08 mg in 20 mL solvent A)

![20 mM](https://user-images.githubusercontent.com/22663189/144862199-a8f7b075-a987-49b5-9f6b-07b7262d192d.JPG)

Fig. 7 MS for dolivhol standard mix (10 ng/mL) with 20 mM ammonium acetate.

Solvent A: 1 mM Ammonium acetate in mobile phase A (3.854 mg in 20 mL mobile phase A)

### Results

- Increase if ammonium acetate concentration could increase the number of detected Dols. However, the ion intensities are reduced at high ammonium acetate concentration (e.g., 20 mM).

### Conclusion

- 10 ng/mL Dol standard mix is not a good reference for ammonium acetate concentration comparison. Need to re-do it with 1000 ng/mL Dol standard mix.

### Experiment 2

- 1, 2, 3, 5 mM ammonium acetate were used to prepare 1000 ng/mL Dol standard mix, and they were directly infused in MS. MS spectrum was acquired for 1 min and they were used for comparison.

### Results 2

![1mM](https://user-images.githubusercontent.com/22663189/144999320-52ee5739-d1a3-405f-abfd-cbd4d1adb4a4.png)

Fig. 8. Averaged MS spectrum of Dol mix with 1 mM Ammonium acetate

![2mM](https://user-images.githubusercontent.com/22663189/145000000-f37678c0-d091-4477-b5bd-f5a9e3ea500a.png)

Fig. 9. Averaged MS spectrum of Dol mix with 2 mM Ammonium acetate

![3mM](https://user-images.githubusercontent.com/22663189/145001560-04e20442-f778-43f0-ae2c-24ec9a3e9048.png)

Fig. 10. Averaged MS spectrum of Dol mix with 3 mM Ammonium acetate

![5mM](https://user-images.githubusercontent.com/22663189/145001758-df24cbfb-f5af-44cd-9605-dfafc0bff2b7.png)

Fig. 11. Averaged MS spectrum of Dol mix with 5 mM Ammonium acetate

- The increase of ammonium acetate leads to the reduction of total ion intensity. 1mM ~= 2 mM > 3 mM > 5mM
- The increase of ammonium acetate could increase the detection of Dols, especially Dol-13 and Dol-21. 1mM < 2 mM ~= 3mM > 5mM

### Conclusion2

Based on above results, addition of 2mM ammonium acetate gives the best result.

**Comment by YonghuiDong** [comment]
## LCMS of Dolichols  (:white_check_mark:)

-----

### Update

**17th, Jan, 2022**:  The method [here](https://github.com/YonghuiDong/BCDD_Research/issues/6#issuecomment-963048077) did not work, because we do not have a BEH Amide C18 column as described in the reference method.

-----

**23rd, Jan, 2022**

### Materials and Method

**Std**: 2000 ng/ml Dol standards, prepared in Solvent A

**Column**: HSS T3, 100 Å, 1.8 μm (particle size), 150 μm × 100 mm

**Mobile phase A**: methanol/acetonitrile (3:1, v/v), with 10 mM ammonium formate + 0.1% formic acid 

**Mobile phase B**: isopropanol/acetonitrile (3:1, v/v) containing 10 mM ammonium formate + 0.1% formic acid


|Time (min)  | Flow (ml/min) | A% | B% |
| ------------- | ------------- | ------------- |------------- |
| 0 | 0.3 | 82| 18  | 
| 2 | 0.3 | 82 | 18  | 
| 16 | 0.3 | 11  | 89 | 
| 20 | 0.3 | 11 | 89  | 
| 25 | 0.3 | 82 | 18 | 
| 35| 0.3 | 82 | 18 | 

Ref:

[Ref1.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7920211/Ref1.pdf)

[Ref2.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7920215/Ref2.pdf)

![Screen Shot 2022-01-23 at 12 16 19](https://user-images.githubusercontent.com/22663189/150673921-ed5a7e9f-4fc6-4e9f-84ca-5e3a1f24a54c.png)

Fig S5 from Ref 2


### Result

Dols can be separated and detected. But the sensitivity is not so good. Further optimization is needed.

- The probable reason that the dolichol ion intensity is low is due to the high amount of ammonium formate. See [here](https://github.com/YonghuiDong/BCDD_Research/issues/6#issuecomment-986622959)
- I need to reduce the ammonium formate to 2mM in the mobile phase.

![Dols](https://user-images.githubusercontent.com/22663189/150686352-33ee88bd-50ec-4f49-8e82-02e866c76848.png)

-----

**24th, Jan, 2022**

**Mobile phase A**: methanol/acetonitrile (3:1, v/v), with 2 mM ammonium formate + 0.1% formic acid 

**Mobile phase B**: isopropanol/acetonitrile (3:1, v/v) containing 2 mM ammonium formate + 0.1% formic acid

### Result

LC chromatograms of Dols (Full scan)

![Dols_2mM](https://user-images.githubusercontent.com/22663189/150816539-d5254a0d-9bf6-4ca3-82e5-485ba744a7ef.png)

The ion intensities of Dols did not improve much when using 2mM ammonium formate. So I decided to use SIM mode. Below is the result:

- Peak shape is better but ion intensity only improved a bit

![Dols_2mM_SIM](https://user-images.githubusercontent.com/22663189/150829067-20d60f41-873f-4fee-9512-7adae6672107.png)

---

**25th, Jan, 2022**

To check again if negative ion mode gives better ionization of Dols.

### Result

Similar as studied by MS only, negative is not as good as positive for Dols detection

![Dol_neg_Sim](https://user-images.githubusercontent.com/22663189/150992419-3321576d-b5ac-4af8-83ff-be99db5227c8.png)
