### ISSUE TITLE
2021_Yeast Metabolomics

### ISSUE THREAD

**Issue by YonghuiDong** [YonghuiDong/BCDD_Research#7]
## Objective

- C18 Metabolomics of yeast samples, with a particular focus on  Phenylalanine, tyrosine, leucine, isoleucine, valine, adenine, adenosine, and glycine.
- Dana wants to compare which extraction method is better

## Todo and Progress

- [x] Sample Analysis (Date: 2021-Nov-11)
- [x] Data Analysis (Date: 2021-Nov-14)
- [x] Report (Date: 2021-Nov-14)

**Comment by YonghuiDong** [comment]
## Sample Analysis

Metabolomics [HSST3 method](https://github.com/YonghuiDong/BCDD_Research/issues/1), positive and negative ion modes.

### Samples: 

There are 14 samples in total

![WechatIMG33](https://user-images.githubusercontent.com/22663189/141380980-fb63ed33-2773-4b1c-a0c4-9f3a52085e64.jpeg)

Fig.1 Yeast samples. The sample naming from Dana is not so clear, so I assigned a label to each sample group.

Table 1. Sample information

|Samples  | Label | Replicates | Note |
| ------------- | ------------- | ------------- |------------- |
| WT | WT | 5 | Extraction Method 1 |
| △△ | TT | 5| Extraction Method 1 |
| MeOH + Ade | MeOH+ | no  | Extraction Method 2 |
| MeOH - Ade | MeOH- | no  | Extraction Method 2 |
| △△ + Ade | TT+ | no| Extraction Method 2 |
| △△ - Ade| TT- | no | Extraction Method 2 |

> Note: need to remind her and other collaborators that replicates are very important.

### Extraction

Dana extracted samples by herself using two different methods:

**Extraction Method 1**

-----

Prepare buffers: 

- Buffer 1: 60% methanol/10 mM Tricine, pH 7.4.:
	(for final volume of 50 ml)
	1 ml Tricine stock (0.5 M)
	19 ml DDW
	30 ml Methanol absolute

- Buffer 2: 75% ethanol/0.5 mM Tricine, pH 7.4.:
	(for final volume of 50 ml)
	50 µl Tricine stock (0.5 M)
	12.5 ml DDW (-50 µl)
	37.5 Ethanol absolute

To do:
- Cool both large and small centrifuges to 4°C.
- Heat thermoblock to 80°C.
- Prepare empty 15 ml tubes + 3 Eppendorf tubes. 

(1) 1 ml of mid-log culture (count cells 5X10^6-1X10^7) was rapidly quenched by addition into 4 ml of Buffer 1, that was maintained at -20°C, to stop metabolism. 
(If using more than 1 ml volume of culture – adjust quantity of buffer accordingly while maintaining the correct ratios). 

(2) After 5 min at -20°C, cells were spun at 1,000 g for 3 min at 4°C, washed with 1 ml of the same buffer, and transferred to an Eppendorf tube.

(3) Spin cells at 1,000 g for 3 min at 4°C, clear sup gently using vacuum suction (avoid touching pellet!), and then re-suspended in 1 ml of Buffer 2. 

(4) Intracellular metabolites were extracted by incubating at 80°C for 3 min, followed by incubation at 4°C for 5 min. 

(5) Samples were spun at 20,000 g for 1 min to pellet cell debris, and 0.9 ml of the supernatant was transferred to a new tube. 

(6) After a second spin at 20,000 g for 10 min, 0.8 ml of the supernatant was transferred to a new tube and stored at -80°C until analysis. (Note: make sure that the label on the Eppendorf reads clear!)

**Reference**

[Extraction Method 1.pdf](https://github.com/YonghuiDong/BCDD_Research/files/7523669/Extraction.Method.1.pdf)

-----

**Extraction Method 2**

-----

need to be added

-----
